import {collectSkillDrop, type SkillFile} from './skill-drop.ts'
import {useEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react'
import type {ReactNode} from 'react'
import {Modal} from '@deepseek-ai/dsh-client-ui-primitives/src/Modal.tsx'
import {resolveCapabilities,capabilityIdentity} from '../../capabilities/resolution.ts'
import type {CapabilityRequest,CapabilityResult,InstallPreview,ManagedCapability,UploadFile} from '../../capabilities/model.ts'
import css from './panel.module.css'
export interface PanelProps{state:{getSnapshot():boolean;subscribe(fn:()=>void):()=>void};close():void;request(input:CapabilityRequest):Promise<CapabilityResult>}
type Entry=CapabilityResult['document']['entries'][number]
type Scope=ManagedCapability['scope']
type Form={type:'import'}|{type:'edit';entry:Entry}|{type:'scope';entry:Entry}|{type:'remove';entry:Entry}|{type:'read';entry:Entry;text:string}|{type:'history'}
export function CapabilityPanel(props:PanelProps){const open=useSyncExternalStore(props.state.subscribe,props.state.getSnapshot);return open?<Manager {...props}/>:null}
function Manager({request,close}:PanelProps){
  const [data,setData]=useState<CapabilityResult>();const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const lock=useRef(false),alive=useRef(true),panel=useRef<HTMLDivElement>(null)
  const [tab,setTab]=useState<'skill'|'mcp'>('skill'),[view,setView]=useState('all'),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0),[form,setForm]=useState<Form|null>(null)
  const [scope,setScope]=useState<Scope>({kind:'global'}),[preview,setPreview]=useState<InstallPreview>(),[auto,setAuto]=useState(false),[replace,setReplace]=useState(false),[draft,setDraft]=useState<Entry>(),[args,setArgs]=useState(''),[env,setEnv]=useState(''),[tools,setTools]=useState<string[]>()
  const [restoreIndex,setRestoreIndex]=useState<number|null>(null)
  const input=useRef<HTMLInputElement>(null),folder=useRef<HTMLInputElement>(null)
  async function call(input:CapabilityRequest):Promise<CapabilityResult|undefined>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const result=await request(input);if(alive.current)setData(result);return result}catch(e){if(alive.current)setError(e instanceof Error?e.message:'操作失败，请重试');return undefined}finally{lock.current=false;if(alive.current)setBusy(false)}}
  useEffect(()=>{alive.current=true;void call({action:'list'});return()=>{alive.current=false}},[])
  useEffect(()=>{const timer=setTimeout(()=>{setSearch(query.trim().toLowerCase());setPage(0)},150);return()=>clearTimeout(timer)},[query])
  const closeForm=()=>{if(lock.current)return;if(form){setForm(null);setPreview(undefined);setError('')}else close()}
  useEffect(()=>{
    const previous=document.activeElement as HTMLElement|null;const root=document.getElementById('root');const old=root?.inert??false;if(root)root.inert=true
    panel.current?.focus()
    const key=(event:KeyboardEvent)=>{if(event.key==='Tab'){const nodes=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled):not([type=hidden]),select:not(:disabled),textarea:not(:disabled)');const visible=[...(nodes??[])].filter(n=>n.getClientRects().length>0),first=visible[0],last=visible.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}}
    document.addEventListener('keydown',key,true);return()=>{if(root)root.inert=old;document.removeEventListener('keydown',key,true);previous?.focus()}
  },[])
  const entries=data?.document.entries??[];const projects=data?.projects??[];const revision=data?.document.revision??0
  const label=(range:Scope)=>range.kind==='global'?'全局 · 所有项目':'指定项目 · '+range.projectIds.map(id=>projects.find(p=>p.id===id)?.title??'已移除项目').join('、')
  const results=useMemo(()=>view==='all'?[]:resolveCapabilities(entries,view==='global'?null:view,data?.document.overrides??[]),[entries,view,data?.document.overrides])
  const rows=useMemo(()=>{const source=view==='all'?entries:results.map(r=>r.effective??r.entries[0]!).filter(Boolean);return source.filter(e=>e.kind===tab&&`${e.title} ${e.key} ${e.description}`.toLowerCase().includes(search))},[entries,results,view,tab,search])
  useEffect(()=>{setPage(p=>Math.min(p,Math.max(0,Math.ceil(rows.length/40)-1)))},[rows.length])
  const active=entries.find(e=>e.id===selected)??rows[0];const effective=active?results.find(r=>r.identity===capabilityIdentity(active)):undefined
  const siblings=active?entries.filter(e=>e.kind===active.kind&&e.key===active.key&&e.id!==active.id):[]
  useEffect(()=>{setPage(0);setSelected('');setTools(undefined)},[tab,view,search])
  function openForm(next:Form){setForm(next);setError('');setNotice('');setPreview(undefined);setReplace(false);setRestoreIndex(null);if('entry'in next){setScope(structuredClone(next.entry.scope));setDraft({...next.entry});const m=next.entry.mcp;setArgs(m?.transport==='stdio'?JSON.stringify(m.args,null,2):'[]');setEnv(m?.transport==='stdio'?m.envNames.join('\n'):JSON.stringify(m?.headerEnv??{},null,2))}else setScope(view!=='all'&&view!=='global'?{kind:'projects',projectIds:[view]}:{kind:'global'})}
  async function mutate(input:CapabilityRequest,message='配置已保存；新的会话加载新配置。'){const result=await call(input);if(result){setNotice(message);setForm(null);setPreview(undefined);setTools(undefined)}return result}
  async function filesChosen(source:File[]|Promise<SkillFile[]>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setPreview(undefined);try{
    const files=Array.isArray(source)?source.map(file=>({file,path:file.webkitRelativePath||file.name})):await source
    if(!files.length)throw new Error('请选择包含 SKILL.md 的技能文件夹或文件')
    if(files.length>256||files.reduce((n,f)=>n+f.file.size,0)>8*1024*1024)throw new Error('技能包最多 256 个文件，总大小 8 MB')
    const uploads:UploadFile[]=[]
    for(const {file,path} of files){let buffer:ArrayBuffer;try{buffer=await file.arrayBuffer()}catch{throw new Error(`读取“${path}”失败，请确认文件仍存在且可读取，然后重新选择。`)}const bytes=new Uint8Array(buffer);let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));uploads.push({path,data:btoa(raw)})}
    lock.current=false;if(!alive.current)return;
    const result=await call({action:'preview',files:uploads});if(result?.preview){setPreview(result.preview);setReplace(false);if(auto&&result.preview.files.length===1&&!result.document.entries.some(e=>e.kind==='skill'&&e.key===result.preview!.name))await install(result.preview,result.document.revision)}
  }catch(e){if(alive.current)setError(e instanceof Error?e.message:'文件读取失败')}finally{lock.current=false;if(alive.current)setBusy(false)}}
  function sameScope(a:Scope,b:Scope){return a.kind===b.kind&&(a.kind==='global'||b.kind==='projects'&&[...a.projectIds].sort().join('\n')===[...b.projectIds].sort().join('\n'))}
  const duplicate=preview?entries.find(e=>e.kind==='skill'&&e.key===preview.name&&sameScope(e.scope,scope)):undefined
  async function install(p=preview,r=revision){if(!p)return;if(scope.kind==='projects'&&!scope.projectIds.length){setError('请至少选择一个项目');return}if(duplicate&&!replace){setError('请确认替换同范围的已有技能');return}const result=await mutate({action:'install',token:p.token,scope,expectedRevision:r,...duplicate?{replaceId:duplicate.id}:{}},'技能已安装；新会话可使用。');if(result){setSelected(result.document.entries.find(e=>e.key===p.name&&sameScope(e.scope,scope))?.id??'');setQuery('')}}
  async function save(){if(!draft)return;try{const entry={...draft,scope};if(entry.kind==='mcp'){const m=entry.mcp;if(!m)throw new Error('请选择连接方式');entry.mcp=m.transport==='stdio'?{...m,args:JSON.parse(args),envNames:env.split('\n').map(s=>s.trim()).filter(Boolean)}:{...m,headerEnv:JSON.parse(env||'{}')}}await mutate({action:'save',entry,expectedRevision:revision})}catch(e){setError(e instanceof Error?e.message:'配置格式错误')}}
  function newConnector(){const entry:Entry={id:'',kind:'mcp',key:'',title:'',description:'',scope:{kind:'global'},enabled:true,createdAt:0,updatedAt:0,source:'remote',mcp:{transport:'streamable-http',url:'',headerEnv:{}}};openForm({type:'edit',entry})}
  const formTitle=form?.type==='import'?'导入技能':form?.type==='scope'?'配置生效范围':form?.type==='remove'?'移除配置':form?.type==='read'?'技能说明':form?.type==='history'?'配置历史':draft?.id?'编辑配置':'添加连接器'
  let content:ReactNode
  if(form){content=<div className={css.form}>
    {form.type==='import'&&<>
      {!preview?<><button className={css.drop} disabled={busy} onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!lock.current)void filesChosen(collectSkillDrop(e.dataTransfer))}}>⇧<strong>拖拽文件或点击上传</strong><small>技能文件夹、SKILL.md、Markdown 或 ZIP 技能包</small></button><input ref={input} hidden type="file" accept=".md,.zip" onChange={e=>void filesChosen([...(e.target.files??[])])}/><input ref={folder} hidden type="file" {...{webkitdirectory:''}} multiple onChange={e=>void filesChosen([...(e.target.files??[])])}/><div className={css.actions}><button disabled={busy} onClick={()=>folder.current?.click()}>选择文件夹</button></div><p className={css.muted}>文件夹或 ZIP 中需有 SKILL.md，文件头需包含 name 和 description。自动读取名称，不运行包内脚本。</p></>:<div className={css.card}><h3>{preview.name}</h3><p>{preview.description}</p><small>{preview.files.length} 个文件 · {preview.digest.slice(0,12)}</small><details><summary>查看文件清单</summary><pre>{preview.files.join('\n')}</pre></details>{preview.warnings.map(w=><p key={w} className={css.note}>{w}</p>)}</div>}
      <ScopeEditor value={scope} change={setScope} projects={projects} disabled={busy}/>
      {!preview&&<label className={css.check}><input type="checkbox" checked={auto} disabled={busy} onChange={e=>setAuto(e.target.checked)}/>仅说明文件自动安装（无重复时）</label>}
      {duplicate&&<div className={css.note}>同范围已有 {duplicate.title}。旧文件将保留。<label className={css.check}><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>确认替换已有技能</label></div>}
      <footer><button disabled={busy} onClick={()=>{setForm(null);setPreview(undefined)}}>取消</button>{preview&&<button className={css.primary} disabled={busy} onClick={()=>void install()}>确认安装</button>}</footer>
    </>}
    {form.type==='scope'&&<><ScopeEditor value={scope} change={setScope} projects={projects} disabled={busy}/><div className={css.note}>只改变生效范围，保留原文件。已开始使用配置的会话保持原状，新会话使用新配置。</div><footer><button disabled={busy} onClick={()=>setForm(null)}>取消</button><button className={css.primary} disabled={busy} onClick={()=>void mutate({action:'save',entry:{...form.entry,scope},expectedRevision:revision})}>保存范围</button></footer></>}
    {form.type==='edit'&&draft&&<>
      <label htmlFor="cap-title">名称</label><input id="cap-title" value={draft.title} disabled={busy} onChange={e=>setDraft({...draft,title:e.target.value})}/>
      <label htmlFor="cap-key">连接标识（同标识按项目覆盖全局）</label><input id="cap-key" value={draft.key} disabled={busy||!!draft.id} onChange={e=>setDraft({...draft,key:e.target.value})}/>
      <label htmlFor="cap-transport">连接方式</label><select id="cap-transport" value={draft.mcp?.transport} disabled={busy} onChange={e=>{setDraft({...draft,mcp:e.target.value==='stdio'?{transport:'stdio',command:'',args:[],envNames:[]}:{transport:'streamable-http',url:'',headerEnv:{}}});setEnv('');setArgs('[]')}}><option value="streamable-http">远程 HTTP</option><option value="stdio">本地进程（stdio）</option></select>
      {draft.mcp?.transport==='stdio'?<><label htmlFor="cap-command">启动程序（不经 shell 展开）</label><input disabled={busy} id="cap-command" value={draft.mcp.command} onChange={e=>setDraft({...draft,mcp:{transport:'stdio',command:e.target.value,args:[],envNames:[]}})}/><label htmlFor="cap-args">参数 · JSON 数组</label><textarea disabled={busy} id="cap-args" value={args} onChange={e=>setArgs(e.target.value)}/><label htmlFor="cap-env">转发的环境变量名称 · 每行一个</label></>:<><label htmlFor="cap-url">服务地址</label><input disabled={busy} id="cap-url" value={draft.mcp?.url??''} onChange={e=>setDraft({...draft,mcp:{transport:'streamable-http',url:e.target.value,headerEnv:{}}})}/><label htmlFor="cap-env">请求头 → 环境变量名称 · JSON 对象</label></>}
      <textarea disabled={busy} id="cap-env" value={env} placeholder={draft.mcp?.transport==='stdio'?'MY_TOKEN':'{"Authorization": "MCP_AUTHORIZATION"}'} onChange={e=>setEnv(e.target.value)}/><p className={css.note}>此处填写环境变量名称，不填写密钥本身。测试连接或首次使用会启动配置的进程/连接服务，请确认来源可信。MCP 进程本身具有当前用户权限，工具调用沿用 DSH 的审批流程。</p>
      <ScopeEditor value={scope} change={setScope} projects={projects} disabled={busy}/><footer><button disabled={busy} onClick={()=>setForm(null)}>取消</button><button className={css.primary} disabled={busy} onClick={()=>void save()}>保存</button></footer>
    </>}
    {form.type==='remove'&&<><h3>{form.entry.title}</h3><p>{label(form.entry.scope)}</p><p className={css.note}>只从管理配置中移除，保留安装文件和配置历史。{siblings.some(e=>e.scope.kind==='global')&&form.entry.scope.kind==='projects'?'移除项目配置后，将恢复使用同标识的全局配置。':''}</p><footer><button disabled={busy} onClick={()=>setForm(null)}>取消</button>{view!=='all'&&view!=='global'&&<button disabled={busy} onClick={()=>void mutate({action:'remove',id:form.entry.id,expectedRevision:revision,disableInProject:view})}>移除并在此项目停用</button>}<button className={css.danger} disabled={busy} onClick={()=>void mutate({action:'remove',id:form.entry.id,expectedRevision:revision},'配置已移除，文件和历史记录保留。')}>确认移除{form.entry.scope.kind==='projects'&&siblings.some(e=>e.scope.kind==='global')?'，恢复全局':''}</button></footer></>}
    {form.type==='read'&&<><pre>{form.text}</pre><footer><button onClick={()=>setForm(null)}>返回</button></footer></>}
    {form.type==='history'&&<><p className={css.note}>恢复名称、生效范围、启用状态与连接配置；技能安装内容保持最新保留版本。</p>{!data?.document.history.length?<div className={css.empty}>暂无变更记录</div>:data.document.history.map((h,index)=><div className={css.card} key={`${h.time}-${index}`}><strong>{h.label}之前</strong><p className={css.muted}>{new Date(h.time).toLocaleString()}</p>{restoreIndex===index?<><p>确认恢复到这次修改之前？当前配置也会保留在历史中。</p><button disabled={busy} onClick={()=>void mutate({action:'restore',index,expectedRevision:revision})}>确认恢复</button><button disabled={busy} onClick={()=>setRestoreIndex(null)}>取消</button></>:<button disabled={busy} onClick={()=>setRestoreIndex(index)}>恢复此配置</button>}</div>)}</>}
  </div>}else{content=<>
    <div className={css.tabs}><button className={tab==='skill'?css.selected:''} onClick={()=>setTab('skill')}>技能 Skills</button><button className={tab==='mcp'?css.selected:''} onClick={()=>setTab('mcp')}>连接器 MCP</button><button onClick={()=>openForm({type:'history'})}>配置历史</button></div>
    <div className={css.toolbar}><input aria-label="搜索技能或连接器" placeholder="搜索名称、标识或描述" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="查看生效范围" value={view} onChange={e=>setView(e.target.value)}><option value="all">全部配置</option><option value="global">全局配置</option>{projects.map(p=><option key={p.id} value={p.id}>生效于：{p.title}</option>)}</select><button disabled={busy} onClick={()=>void call({action:'list'})}>刷新</button><button className={css.primary} disabled={busy||!data} onClick={()=>tab==='skill'?openForm({type:'import'}):newConnector()}>＋ {tab==='skill'?'导入技能':'添加连接器'}</button></div>
    <div className={css.body}><div className={css.list}>
      {!rows.length&&<div className={css.empty}>{busy?'正在加载…':query?'没有匹配结果':'暂无配置'}<p>{tab==='skill'?'导入技能后，在这里管理生效范围。':'添加远程服务或本地 MCP 进程。'}</p></div>}
      {rows.slice(page*40,(page+1)*40).map(e=>{const r=results.find(r=>r.identity===capabilityIdentity(e));return <button key={e.id} className={`${css.row} ${active?.id===e.id?css.selected:''}`} onClick={()=>{setSelected(e.id);setTools(undefined)}}><strong>{e.title}</strong><small>{e.description||e.key}</small><span className={css.pill}>{label(e.scope)}</span><span className={css.pill}>{r?.status==='conflict'?'配置冲突':(r?r.status==='enabled':e.enabled)?'已启用':'已停用'}</span>{r?.shadowed.length?<small>另有 {r.shadowed.length} 份配置</small>:null}</button>})}
      {rows.length>40&&<div className={css.pagination}><button disabled={!page} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{page+1} / {Math.ceil(rows.length/40)}</span><button disabled={(page+1)*40>=rows.length} onClick={()=>setPage(p=>p+1)}>下一页</button></div>}
    </div><div className={css.detail}>{!active?<div className={css.empty}>选择一项查看详情</div>:<>
      <h2>{active.title}</h2>{effective?.effective&&effective.effective.id!==active.id&&<p className={css.note}>正在查看其他来源；此项目实际使用「{effective.effective.title}」。</p>}<small>{active.key}</small><p className={css.muted}>{active.description}</p>
      <div className={css.line}><span>{view==='all'||view==='global'?'配置启用状态':'此项目启用状态'}</span><button role="switch" aria-checked={effective?effective.status==='enabled':active.enabled} disabled={busy} onClick={()=>{if(view!=='all'&&view!=='global')void mutate({action:'override',override:{kind:active.kind,key:active.key,projectId:view,mode:effective?.status==='enabled'?'disabled':'enabled'},expectedRevision:revision});else void mutate({action:'save',entry:{...active,enabled:!active.enabled},expectedRevision:revision})}}>{(effective?effective.status==='enabled':active.enabled)?'已启用':'已停用'}</button></div>
      {effective&&<div className={css.note}>{effective.status==='conflict'?'同范围存在重复配置，请处理后再使用。':effective.reason==='project-disabled'?'仅在此项目停用，全局配置保持不变。':effective.reason==='explicit-inherit'?'此项目明确使用全局配置。':effective.reason==='project'?'当前使用项目配置；同标识全局配置不会同时加载。':'当前继承全局配置。'}</div>}
      <div className={`${css.card} ${css.scope}`}><div className={css.line}><strong>生效范围</strong><button disabled={busy} onClick={()=>openForm({type:'scope',entry:active})}>配置范围</button></div><p>{label(active.scope)}</p>{active.scope.kind==='global'&&<small>包含以后新增的项目；有项目覆盖的条目按项目配置执行。</small>}</div>
      <div className={css.card}><h3>来源与版本</h3><span className={css.pill}>{active.kind==='skill'?'本地文件':active.mcp?.transport==='stdio'?'外部程序':'远程服务'}</span><p>{active.kind==='skill'?'本地导入 · 无发布版本':active.mcp?.transport==='stdio'?'外部安装方式维护版本':'服务方维护版本'}</p><small>配置更新：{new Date(active.updatedAt).toLocaleString()}</small>{active.digest&&<p className={css.code}>内容指纹 {active.digest.slice(0,16)}</p>}<pre>{active.path??(active.mcp?.transport==='stdio'?`${active.mcp.command}\n${JSON.stringify(active.mcp.args)}`:active.mcp?.url)}</pre></div>
      {siblings.length>0&&<details className={css.versions}><summary>查看其他来源 · {siblings.length} 份</summary>{siblings.map(e=><button key={e.id} onClick={()=>setSelected(e.id)}>{label(e.scope)} · {e.enabled?'启用':'停用'}<br/><small>{e.path??e.key}</small></button>)}{view!=='all'&&view!=='global'&&<div className={css.actions}><button disabled={busy} onClick={()=>void mutate({action:'override',override:{kind:active.kind,key:active.key,projectId:view,mode:'inherit'},expectedRevision:revision})}>此项目使用全局</button><button disabled={busy} onClick={()=>void mutate({action:'override',override:{kind:active.kind,key:active.key,projectId:view,mode:'project'},expectedRevision:revision})}>恢复项目优先</button></div>}</details>}
      {tools&&<div className={css.note}>连接成功 · {tools.length} 个工具<pre>{tools.join('\n')}</pre></div>}
      <div className={css.actions}>{active.kind==='skill'?<button disabled={busy} onClick={()=>{void call({action:'read',id:active.id}).then(r=>{if(r)openForm({type:'read',entry:active,text:r.text??''})})}}>查看技能说明</button>:<><button disabled={busy} onClick={()=>{setTools(undefined);void call({action:'test',id:active.id}).then(r=>{if(r)setTools(r.tools??[])})}}>测试连接</button><button disabled={busy} onClick={()=>openForm({type:'edit',entry:active})}>编辑配置</button></>}<button className={css.danger} disabled={busy} onClick={()=>openForm({type:'remove',entry:active})}>移除…</button></div>
      <p className={css.note}>正在运行的会话保留原配置。请新建会话使用保存后的技能与连接器。原生插件已占用的 MCP 标识需先在原插件中停用，避免工具冲突。</p>
    </>}</div></div></>}
  return <Modal open onClose={closeForm} title={form?formTitle:'技能和连接器'} headless className={css.modal??''}><div ref={panel} tabIndex={-1} className={css.panel} aria-busy={busy}><header><div><h2>{form?formTitle:'技能和连接器'}</h2><small>{form?'安装与配置会保存到本机':'全局管理入口 · 每项独立配置生效范围'}</small></div><button aria-label={form?'返回管理列表':'关闭管理面板'} disabled={busy} onClick={closeForm}>×</button></header>{error&&<div role="alert" className={css.error}>{error}<button disabled={busy} onClick={()=>void call({action:'list'})}>刷新配置</button></div>}{notice&&<div role="status" className={css.status}>{notice}</div>}{busy&&<div role="status" className={css.status}>正在处理，请稍候…</div>}{content}<div className={css.footer}>技能与 MCP 配置使用 DSH；文件安装不执行脚本。修改后的范围在新会话生效。</div></div></Modal>
}
function ScopeEditor({value,change,projects,disabled}:{value:Scope;change(scope:Scope):void;projects:CapabilityResult['projects'];disabled:boolean}){
  const [query,setQuery]=useState('')
  return <section><h3>生效范围</h3><div className={css.radioRow}><label><input type="radio" name="cap-scope" disabled={disabled} checked={value.kind==='global'} onChange={()=>change({kind:'global'})}/> 全局</label><label><input type="radio" name="cap-scope" disabled={disabled} checked={value.kind==='projects'} onChange={()=>change({kind:'projects',projectIds:[]})}/> 指定项目</label></div>{value.kind==='global'?<p className={css.muted}>所有项目可用，包含以后新增的项目。</p>:<><input aria-label="搜索项目" placeholder="搜索项目" value={query} onChange={e=>setQuery(e.target.value)}/><div className={css.projectList}>{projects.filter(p=>`${p.title} ${p.path}`.toLowerCase().includes(query.toLowerCase())).map(p=><label className={css.check} key={p.id}><input type="checkbox" disabled={disabled} checked={value.projectIds.includes(p.id)} onChange={e=>change({kind:'projects',projectIds:e.target.checked?[...value.projectIds,p.id]:value.projectIds.filter(id=>id!==p.id)})}/><span>{p.title}<br/><small>{p.path}</small></span></label>)}{!projects.length&&<p>暂无项目，请先创建工作区。</p>}</div><small>已选 {value.projectIds.length} 个项目</small></>}</section>
}
